-- ASLingo Live Recognition Learning v1
create table if not exists public.recognition_feedback (
  id bigint generated by default as identity primary key,
  user_id text not null,
  session_id text not null,
  model_version text not null default 'signbridge-static-v2',
  feedback_kind text not null check (feedback_kind in ('confirmed','corrected')),
  predicted_label text not null check (predicted_label ~ '^[A-Z]$'),
  actual_label text not null check (actual_label ~ '^[A-Z]$'),
  features jsonb not null,
  model_scores jsonb not null,
  predicted_score real,
  predicted_margin real,
  handedness text,
  tracking_score real,
  sample_quality real,
  device_class text,
  platform text,
  browser_family text,
  camera_width integer,
  camera_height integer,
  aspect_ratio real,
  created_at timestamptz not null default now()
);

alter table public.recognition_feedback enable row level security;
grant select, insert on public.recognition_feedback to authenticated;

create policy recognition_feedback_insert_own
on public.recognition_feedback
for insert to authenticated
with check (auth.user_id() = user_id);

create policy recognition_feedback_read_own
on public.recognition_feedback
for select to authenticated
using (auth.user_id() = user_id);

create index if not exists recognition_feedback_user_created_idx on public.recognition_feedback (user_id, created_at desc);
create index if not exists recognition_feedback_actual_created_idx on public.recognition_feedback (actual_label, created_at desc);
create index if not exists recognition_feedback_confusion_idx on public.recognition_feedback (predicted_label, actual_label, created_at desc);

create or replace view public.recognition_community_samples with (security_barrier=true) as
select
  id,
  substr(md5(user_id || ':aslingo-recognition-community-v1'), 1, 20) as contributor_token,
  actual_label as label,
  predicted_label,
  feedback_kind,
  features,
  sample_quality,
  device_class,
  model_version,
  created_at
from public.recognition_feedback;

grant select on public.recognition_community_samples to authenticated;
